version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "19:00"
      timezone: Europe/Madrid
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: weekly
      time: "19:00"
      timezone: Europe/Madrid
  - package-ecosystem: "pub"
    directory: "elementary/"
    schedule:
      interval: weekly
      time: "19:00"
      timezone: Europe/Madrid
