name: melos_rack_workspace
publish_to: none

repository: https://github.com/coolosos/elementary_ui
issue_tracker: https://github.com/coolosos/elementary_ui/issues
homepage: https://github.com/coolosos

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.6"

dev_dependencies:
  melos: ^6.0.0
  coolint: 2.0.0
