name: elementary_ui
description: "A components with Kind provider."

repository: https://github.com/coolosos/elementary_ui
issue_tracker: https://github.com/coolosos/elementary_ui/issues
homepage: https://github.com/coolosos

version: 0.0.3

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0
  collection: ^1.18.0
  equatable: ^2.0.5
  nested: ^1.0.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 1.0.3
