name: elementary_ui
description: "A components with Kind provider."

version: 0.0.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: any
  collection: any
  equatable: any
  nested: ^1.0.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 1.0.3
